apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "azp-agent.fullname" . }}
  labels:
    app: {{ include "azp-agent.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "azp-agent.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "azp-agent.name" . }}
    spec:
      containers:
        - name: azp-agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AZP_URL
              value: "{{ .Values.azure.url }}"
            - name: AZP_POOL
              value: "{{ .Values.azure.pool }}"
            - name: AZP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.tokenSecretName }}
                  key: token


          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
