apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: { { .Values.patSecretName } }
  namespace: { { .Release.Namespace } }
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    pat: { { .Values.sealedPat | quote } }
