apiVersion: v1
kind: Service
metadata:
  name: {{ include "azp-agent.fullname" . }}
spec:
  selector:
    app: {{ include "azp-agent.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
